#ifndef CONSTANTS_H
#define CONSTANTS_H

enum class Status {
  CAN_INIT_START,
  CAN_INIT_OPEN_SOCKET_FAILED,
  CAN_INIT_SETTING_SOCKET_FAILED,
  CAN_INIT_BINDING_SOCKET_FAILED,
  CAN_INIT_NUM_CHANNEL_FAILED,
  CAN_INIT_SUCCESS,
  CAN_RECONFIG_START,
  CAN_RECONFIG_LINUX_SUCCESS,
  CAN_RECONFIG_NUM_CHANNEL_FAILED,
  CAN_RECONFIG_FILTERED_FAILED,
  CAN_RECONFIG_FILTERED_SUCCESS,
  CAN_RECONFIG_READ_FILTERED_SUCCESS,
  CAN_READ_START,
  CAN_READ_NO_DATA,
  CAN_READ_SUCCES,
  CAN_START_READ_NUM_CHANNEL_FAILED,
  CAN_START_READ_SUCCES,
  CAN_STOP_READ_NUM_CHANNEL_FAILED,
  CAN_STOP_READ_FAILED,
  CAN_STOP_READ_SUCCES,
  CAN_WRITE_START,
  CAN_WRITE_MSG_EMPTY,
  // CAN_WRITE_MSG_NOT_EMPTY ,
  CAN_WRITE_GET_MSG_SUCCES,
  CAN_WRITE_FAILED,
  CAN_WRITE_SECCES,
  CAN_START_WRITE_SECCES,
  CAN_STOP_WRITE_FAILED,
  CAN_STOP_WRITE_SECCES,
  CAN_SOCKET_STOP_NUM_CHANNEL_FAILED,
  CAN_SOCKET_STOP_FAILED,
  CAN_SOCKET_STOP_SUCCES

};

// Q_ENUM(Status)

#endif // CONSTANTS_H
